[package]
name = "express-vpn"
version = "0.1.0"
authors = ["kunicmarko20 <kunicmarko20@gmail.com>"]
edition = "2018"

[dependencies]
dirs="1.0.4"
glib="0.5.0"
gtk="0.4.0"
gtk-sys="0.6.0"
libappindicator="0.4.0"
arc_guard = { path = "arc_guard" }
