[package]
name = "express-vpn-gui"
version = "0.1.0"
authors = ["kunicmarko20 <kunicmarko20@gmail.com>"]
edition = "2018"

[dependencies]
arc-guard = "0.1.0"
clap = "2.32.0"
dirs="1.0.4"
glib="0.5.0"
gtk="0.4.0"
gtk-sys="0.6.0"
libappindicator="0.4.0"
libc = "0.2.49"
structopt = "0.2.13"
